### ISSUE TITLE
Error while executing docker run.

### ISSUE THREAD

**Issue by sandepp123** [nielsen-oss/fasttext-serving#8]
I was trying to follow through the [Quickstart] (https://github.com/nielsen-oss/fasttext-serving#quick-start) and getting error while I execute the "docker run" command, the traceback is as follows.
            `Traceback (most recent call last):
                  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
                  return _run_code(code, main_globals, None,
                  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
                  exec(code, run_globals)
                  File "/usr/src/app/fts/__main__.py", line 84, in <module>
                   serve()
                File "/usr/src/app/fts/__main__.py", line 58, in serve
                 servicer = FastTextServicer()
                    File "/usr/src/app/fts/server/server.py", line 23, in __init__
            self._fasttext_service = FastTextService()
          File "/usr/src/app/fts/service/fasttext_service.py", line 56, in __init__
            self._observer.start()
          File "/usr/local/lib/python3.8/site-packages/watchdog/observers/api.py", line 253, in start
            emitter.start()
          File "/usr/local/lib/python3.8/site-packages/watchdog/utils/__init__.py", line 110, in start
            self.on_thread_start()
          File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
            self._inotify = InotifyBuffer(path, self.watch.is_recursive)
          File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
            self._inotify = Inotify(path, recursive)
          File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 200, in __init__
            self._add_dir_watch(path, recursive, event_mask)
          File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 387, in _add_dir_watch
            raise OSError(errno.ENOTDIR, os.strerror(errno.ENOTDIR), path)
        NotADirectoryError: [Errno 20] Not a directory: b'sample/models' `

I am using 
docker version : Docker version 20.10.18, build b40c2f6
ubuntu 18.04

**Comment by defr8001** [comment]
Try again changing the line:

https://github.com/nielsen-oss/fasttext-serving/blob/master/sample/config.yaml#L19

with:

models_path: /models

This should point to the folder in your container where the fastText models are available.

Regards
